spring:
  application:
    name: task service

  # endereco de conexao com o banco de dados + reconectar, caso caia a conexao.
  datasource:
    url: jdbc:postgresql://localhost:5433/task-service
    username: postgres
    password: pgadmin
    # indica o driver de qual banco de dados esta sendo usando
    dbcp2:
      driver-class-name: org.postgresql.Driver
    # indica a plataforma que esta sendo usado.
    platform: postgres

  # para a gravacao no banco de dados.
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    open-in-view: false

  # Configuracoes do Jackson para datas (para que o backend entenda o formato do frontend)
  jackson:
    serialization:
      write-dates-as-timestamps: false
    date-format: yyyy-MM-dd'T'HH:mm:ss

# logging.level.org.springframework=DEBUG
# debug=true